# Generated by Django 5.0 on 2023-12-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientBlood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=1000)),
                ("patient_email", models.CharField(max_length=1000)),
                ("patient_phone_number", models.CharField(max_length=1000)),
                ("patient_blood_type", models.CharField(max_length=1000)),
                ("patient_health_information", models.CharField(max_length=2000)),
                ("resolved", models.BooleanField(default=False)),
            ],
        ),
    ]
